version: "3.7"
services:
    prestashop:
        build: $PWD/202/docker
        environment:
            PS_DOMAIN: "6602-2a01-e34-ecba-50c0-5115-2479-804c-530.ngrok.io"
            RUN_USER: clotaire
        ports:
            - 8080:80
        volumes:
            - $PWD:/var/www/html/modules/stripe_official
volumes:
  data:

